/*********** Generated on 2016/07/23 22:44:04 by reswrap version 5.3.0 *********/

/* Created by reswrap from file gifanimado.id */
static char gifanimado_id[]=
  "/tmp/gifanimadoXXXXXX"
  ;

/* Created by reswrap from file gifanimado.sh */
static char gifanimado_sh[]=
  "#!/bin/bash\n"
  "   \n"
  "################################################################################"
  "\n"
  "\n"
  "# Tipos de respuestas para todos los protocolos.\n"
  "    REPLY_YES=%s  # Respuesta Si.\n"
  "    REPLY_NO=%s   # Respuesta No.\n"
  "\n"
  "# Protocolos de Error. \n"
  "# Espera una respuesta de parte de NiNo, S\xc3\xad o No.\n"
  "    ERR_Q_PROTO=%s # Error de pregunta.\n"
  "    ERR_I_PROTO=%s # Error de informaci\xc3\xb3n.\n"
  "    ERR_W_PROTO=%s # Error de alerta.\n"
  "\n"
  "# Protocolos de Informaciones.\n"
  "# Espera una respuesta de parte de NiNo, S\xc3\xad solamente.\n"
  "    INFO_PROTO=%s  # Informaci\xc3\xb3n.\n"
  "    WARN_PROTO=%s  # Alerta.\n"
  "\n"
  "# Protocolos de Salida. Silenciosa.\n"
  "# No espera ninguna respuesta de parte de NiNo\n"
  "    QUIT_PROTO=%s  # Salir de NiNo\n"
  "\n"
  "# Delimitador de formato   \n"
  "    DELIM=%s\n"
  "#########################################################################\n"
  "\n"
  "    fifo=%s  \n"
  "    retraso=%s\n"
  "    repetir=%s  \n"
  "\n"
  "# Ubicaci\xc3\xb3n y nombre del archivo gif\n"
  "    gifanimado=\"%s\"\n"
  "\n"
  "# Lista de archivos de im\xc3\xa1genes a convertir.\n"
  "    lista_imgs=\"%s\"\n"
  "\n"
  "    app=convert\n"
  "#########################################################################\n"
  "    \n"
  "    function BeforeConvert () {\n"
  "\t\n"
  "\tif [ ! -x /usr/bin/$app ]; then\n"
  "\t    titulo=\"GifAnimado - Error\"\n"
  "\t    mensaje=\"No se encontr\xc3\xb3 /usr/bin/$app.\"\n"
  "\t    echo $WARN_PROTO$DELIM$titulo$DELIM$mensaje > $fifo\n"
  "\t    sync\n"
  "\t    read -n 1 continuar < $fifo\n"
  "\t    return 0\n"
  "\tfi\n"
  "\n"
  "\tif [ -e `pwd`/$gifanimado ]; then\n"
  "\t    titulo=\"GifAnimado - Pregunta\"\n"
  "\t    mensaje=\"Ya existe el archivo $gifanimado. \xc2\xbfSobrescribirlo?\"\n"
  "\t    echo $ERR_Q_PROTO$DELIM$titulo$DELIM$mensaje > $fifo\n"
  "\t    sync\n"
  "\t    read -n 1 continuar < $fifo\n"
  "\t    if [ \"$continuar\" == \"$REPLY_NO\" ]; then \n"
  "\t\treturn 0\n"
  "\t    fi\n"
  "\tfi\n"
  "\treturn 1\n"
  "    }\n"
  "\n"
  "    function Convert () {\n"
  "\t\tlocal imgs=$(echo $lista_imgs | sed \"s/'/ /g\") # Elimina el caract. '\n"
  "\n"
  "\t\t$app -delay $retraso -loop $repetir $imgs  $gifanimado\n"
  "\t\t\n"
  "\t\tif [ $? == 1 ]; then\n"
  "\t\t\ttitulo=\"GifAnimado - Error\"\n"
  "\t\t\tmensaje=\"Ocurri\xc3\xb3 un error al ejecutar '$app'\"\n"
  "\t\t\t\n"
  "\t\t\techo $WARN_PROTO$DELIM$titulo$DELIM$mensaje > $fifo\n"
  "\t\t\tsync\n"
  "\t\t\t\n"
  "\t\t\tread -n 1 continuar < $fifo\n"
  "\t\telse\n"
  "\t\t\ttitulo=\"GifAnimado - Informaci\xc3\xb3n\"\n"
  "\t\t\tmensaje=\"La conversi\xc3\xb3n termin\xc3\xb3.\" \n"
  "\t\t\t\n"
  "\t\t\techo $INFO_PROTO$DELIM$titulo$DELIM$mensaje > $fifo\n"
  "\t\t\tsync\n"
  "\t\t\t\n"
  "\t\t\tread -n 1 continuar < $fifo\n"
  "\t\t\t\n"
  "\t\t\t\techo $QUIT_PROTO$DELIM$REPLY_YES > $fifo\n"
  "\t\t\t\tsync\n"
  "\t\tfi\n"
  "    }\n"
  "\n"
  "\n"
  "########################################################################\n"
  "\n"
  "BeforeConvert;\n"
  "\n"
  "if [ \"$?\" == \"1\" ]; then\n"
  "    Convert;\n"
  "fi\n"
  "\n"
  "exit 0\n"
  "########################################################################\n"
  ""
  ;

